POST https://nadastestert.onrender.com/api/parties
Content-Type: application/json

{
   "title": "Festa legal",
   "authot": "Patricio",
   "description": "Minha festa",
   "budget": 5000
}

###
GET https://nadastestert.onrender.com/api/parties/